Mini Project/productreview/productreview/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from user.urls import urlpatterns as user_urls
from admins.urls import urlpatterns as admins_urls
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'',include(user_urls, namespace='users'),name='users'),
    url(r'^admins/',include(admins_urls, namespace='admins'),name='admins'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Mini Project/productreview/user/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views as ind_views
from .forms import CustomAuthForm

urlpatterns = [
    url(r'^home$',ind_views.home,name='home'),
    url(r'^$',auth_views.login,{'template_name': 'login.html',"authentication_form":CustomAuthForm}, name='login'),
    url(r'^logout/$',auth_views.logout, {'next_page': 'users:login'}, name='logout'),
    url(r'^registration/$',ind_views.registration, name='registration'),
    url(r'^Your/Orders/$',ind_views.yourorders,name='yourorders'),
    url(r'^Confirmed/Orders/$',ind_views.confirmproducts,name='confirmedorders'),
    url(r'^chechouts/$',ind_views.chechouts,name='chechouts'),
    url(r'^view-ratings/(?P<pk>\d+)$',ind_views.viewratings,name='viewratings'),
    url(r'^Product/List/$',ind_views.productlist,name='productlist'),
    url(r'^Top/Products/$',ind_views.topproducts,name='topproducts'),
    url(r'^Graphs/$',ind_views.graphs,name='graphs'),
]

Mini Project/productreview/assets/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en" >

<head>
  <meta charset="UTF-8">
  <title>CSS3 MENU BUILD</title>
      <link rel="stylesheet" href="{% static 'css/style.css' %}">

  
</head>

<body style="background:url({% static 'images/2.jpg' %});">

      <ul>
        <li class="active" style="width: 16.6666666666667%"><a href="{% url 'users:home' %}" target="">Home</a></li>

        <li style="width: 16.6666666666667%"><a href="{% url 'users:yourorders' %}" target="">Your Orders</a></li>

        <li style="width: 16.6666666666667%"><a href="{% url 'users:confirmedorders' %}" target="">Confirmed Products</a></li>

        <li style="width: 16.6666666666667%"><a href="{% url 'users:productlist' %}" target="">Product List</a></li>
        
        <li style="width: 16.6666666666667%"><a href="{% url 'users:topproducts' %}" target="">Top Products</a></li>

        <li style="width: 16.6666666666667%"><a href="{% url 'users:graphs' %}" target="">Graphs</a></li>

        <li style="width: 16.6666666666667%"><a href="{% url 'users:logout' %}" target="">Logout</a></li>
    </ul>
  
  <div style="margin-top:-400px;margin-left:400px;">
    {% block userbody %}
    {% endblock %}
    </div>
    

</body>

</html>

Mini Project/productreview/assets/templates/baselog.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en" >

<head>
  <meta charset="UTF-8">
  <title>CSS3 MENU BUILD</title>
        
</head>

<body style="background:url({% static 'images/2.jpg' %});">

{% block loginbody %}
{% endblock %}

</body>

</html>

Mini Project/productreview/assets/templates/confirmed.html
{% extends 'base.html' %}
{% block userbody %}
{% load staticfiles %}
<style>

.titlebar
{
padding:10px;
width:97%;
height:80px;
background:rgba(94, 142, 137,0.8);
margin-bottom:20px;
border:2px solid rgb(241, 103, 103);
border-radius:10px;
}
div.titlebar img.usicon{
position:relative;
left:17%;
}
div.titlebar img.caicon{
position:relative;
margin-left:3%;
}
@font-face {
    font-family: Lobster;
    src: url({% static 'fonts/Lobster.otf' %});
}
.para{
text-align:center;
//text-transform:uppercase;
font-size:30px;
width:100%;
float:left;
margin-top:0px;
color:white;
font-family:Lobster;
}
.containersd{
width:100%;
margin-left:-50px;
}
.outercas{
height:100%;
width:100%;
background:rgba(94, 142, 137,0.6);
overflow:auto;
border:2px solid rgb(241, 103, 103);
border-radius:10px;
}
</style>
<div class="containersd">
<div class="titlebar">
<p class="para">Weakly-supervised Deep Embedding for Product Review Sentiment Analysis</p>
</div>
<div class="outercas">
<table>
<tr>
    <th>Product Name</th>
    <th>Image</th>
    <th>Qty</th>
    <th>Location</th>
    <th>Ordered Date</th>
    <th>Status</th>
</tr>
{% for pr in prod %}
<tr>
<td>{{pr.prod.name}}</td>
<td><img src="{{pr.prod.images.url}}" style="width:100px;height:100px;" /></td>
<td>{{pr.prodqty}}</td>
<td>{{pr.location}}</td>
<td>{{pr.dateordered}}</td>
<td>
{{pr.status}}
</td>
{% endfor %}
</tr>
</table>
{% endblock %}

Mini Project/productreview/assets/templates/graphs.html
{% extends 'base.html' %}
{% block userbody %}
{% load staticfiles %}

<style>

.titlebar
{
padding:10px;
width:95%;
height:80px;
background:rgba(94, 142, 137,0.8);
margin-bottom:20px;
margin-left:-50px;
border:2px solid rgb(241, 103, 103);
border-radius:10px;
}

@font-face {
    font-family: Lobster;
    src: url({% static 'fonts/Lobster.otf' %});
}
.para{
text-align:center;
//text-transform:uppercase;
font-size:30px;
width:100%;
float:left;
margin-top:0px;
color:white;
font-family:Lobster;
}

.outercas{
margin:center;
height:100%;
width:98%;
padding:10px;
background:rgba(94, 142, 137,0.6);
overflow:auto;
border:2px solid rgb(241, 103, 103);
border-radius:10px;
margin-left:-50px;
}

</style>
<script>
window.onload = function () {

var chart = new CanvasJS.Chart("chartContainer", {
	animationEnabled: true,
	title:{
		text: "Products Purchased",
		horizontalAlign: "left"
	},
	data: [{
		type: "doughnut",
		startAngle: 60,
		//innerRadius: 60,
		indexLabelFontSize: 17,
		indexLabel: "{label} - #percent%",
		toolTipContent: "<b>{label}:</b> {y} (#percent%)",
		dataPoints: [
        {% for p in prod %}
			{ y: {{p.ratings}}, label: "{{p.product__name}}" },
			/*{ y: 67, label: "Inbox" },
			{ y: 28, label: "Archives" },
			{ y: 10, label: "Labels" },
			{ y: 7, label: "Drafts"},
			{ y: 15, label: "Trash"},
			{ y: 6, label: "Spam"}*/
        {% endfor %}
		]
	}]
});
chart.render();

}
</script>

<div class="titlebar">
<p class="para">Weakly-supervised Deep Embedding for Product Review Sentiment Analysis</p>
</div>
<div class="outercas">
<div id="chartContainer" style="height: 370px; max-width: 920px; margin: 0px auto;"></div>
<script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
</div>
{% endblock %}

Mini Project/productreview/assets/templates/home.html
{% extends 'base.html' %}
{% block userbody %}
{% load staticfiles %}
<style>
.outercas{
height:100%;
width:100%;
background:rgba(94, 142, 137,0.6);
overflow:auto;
border:2px solid rgb(241, 103, 103);
border-radius:10px;
}
.innerclas:hover{
color:white;
background:rgba(94, 142, 137,0.2);
}
.innerclas{
width:15%;
float:left;
padding:10px;
background:white;
margin:10px;
}
.viewprodlink{
padding:0px;
spacing:0px;
}
.intabl{
width:60%;
margin:auto;
}
.intabl1{
width:60%;
margin:auto;
}

table.intabl tr td{
height:40px;
}
table.intabl1 tr td{
height:40px;
}
.dots{
padding-left:20px;
padding-right:20px;
font-weight:bold;
}
.containersd{
width:100%;
margin-left:-50px;
}
.titlebar
{
padding:20px;
width:100%;
height:100px;
background:rgba(94, 142, 137,0.8);
margin-bottom:20px;
border:2px solid rgb(241, 103, 103);
border-radius:10px;
}
div.titlebar img.usicon{
position:relative;
left:17%;
}
div.titlebar img.caicon{
position:relative;
margin-left:3%;
}
@font-face {
    font-family: Lobster;
    src: url({% static 'fonts/Lobster.otf' %});
}
.para{
text-align:center;
//text-transform:uppercase;
font-size:30px;
width:75%;
float:left;
margin-top:-20px;
color:white;
font-family:Lobster;
}

.comico{
float:left;
padding:0px;
margin:0px;
}
input[type=text],input[type=number]{
visibility:block;
}

</style>
<link rel="stylesheet" href="{% static 'css/bootstrap1.min.css' %}">
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>

<div class="containersd">
<div class="titlebar">
<p class="para">Weakly-supervised Deep Embedding for Product Review Sentiment Analysis</p>
<a href="{% url 'users:yourorders' %}" class="comico" style="margin-left:40px;"><img src="{% static 'images/cart.png' %}" style="width:40px;height:40px;"/></a>
</div>
<div class="outercas">
{% for pro in prod %}
<div class="innerclas">
<img src="{{pro.images.url}}" style="width:100%;height:100px"><br/>
{{pro.name}}<br/>
<a class="viewprodlink"  data-toggle="modal" data-target="#myModal{{pro.id}}">view product</a>
</div>
<div class="modal fade" id="myModal{{pro.id}}" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Product Details</h4>
        </div>
        <div class="modal-body">
            <table>
            <tr>
            <td colspan="2"><img src="{{pro.images.url}}" style="height:250px;width:565px;"/></td>
            </tr>
            <tr>
            <td align="center">
                <table class="intabl">
                <tr>
                <td>Name</td>
                <td><span class="dots">:</span></td>
                <td>{{pro.name}}</td>
            </tr>
            <tr>
                <td>weight</td>
                <td><span class="dots">:</span></td>
                <td>{{pro.weight}}</td>
            </tr>
            <tr>
                <td>color</td>
                <td><span class="dots">:</span></td>
                <td>{{pro.color}}</td>
            </tr>
            <tr>
                <td>price</td>
                <td><span class="dots">:</span></td>
                <td>{{pro.price}}</td>
            </tr>
            <tr>
                <td>category</td>
                <td><span class="dots">:</span></td>
                <td>{{pro.category}}</td>
            </tr>
            <tr>
                <td>stock</td>
                <td><span class="dots">:</span></td>
                <td>
                {% if pro.stock > 0 %}
                <span>{{pro.stock}}</span>
                {% else %}
                <span>No Stock</span>
                {% endif %}
                </td>
            </tr>
            <tr>
                <td>description</td>
                <td><span class="dots">:</span></td>
                <td>{{pro.description}}</td>
                </tr>
                </table>
                </td>
            </tr>
            <tr>
               <td>
                    <table  class="intabl1">
                    <tr>
                    <td colspan="3"><div style="width: 100%; height: 20px; border-bottom: 1px solid black; text-align: center">
      <span style="font-size: 25px; background-color: white; padding: 0 10px;">
        Cart Details<!--Padding is optional-->
      </span>
    </div></td>
                    </tr>
                    <tr>
                    <form method="POST" autocomplete="off">
                    {% csrf_token %}
                    <td><span >Product Quantity</span></td>
                    <td><span class="dots">:</span></td>
                    <td>{{ form.prodqty }}</td>
                    </tr>
                    <tr>
                    <td>Location</td>
                    <td><span class="dots">:</span></td>
                    <td>{{ form.location }}</td>
                    </tr>
                    </table>
               </td>
            </tr>
            </table>          
            <input type="hidden" name="idu" value="{{pro.id}}" style="visibility:none">
        </div>
        <div class="modal-footer">
          <button type="submit" name="addcart" class="btn btn-default">Add To Cart</button>
          </form>
          <a class="btn btn-default" href="{% url 'users:viewratings' pro.id %}">View Ratings</a>
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
      <script>
      function foo()
      {
        window.location = "{% url 'users:viewratings' pro.id %}";
      }
      </script>
    </div>
  </div>
{% endfor %}
</div>
</div>
{% endblock %}

Mini Project/productreview/assets/templates/login.html
{% extends 'baselog.html' %}
{% block loginbody %}
{% load staticfiles %}
<style>
.userna{
    border:1px solid white;
    background:none;
    border-radius:5px;
    text-align:center;
}
.userna:hover{
}
.passwo{
border:1px solid white;
background:none;
border-radius:5px;
text-align:center;
}
input[type="text"].userna::-webkit-input-placeholder,input[type="password"].passwo::-webkit-input-placeholder {
  color: white;
  opacity:1;
}
table tr {
height:50px;

}
input[type=submit].subbtn{
width:50%;
background:none;
border:1px solid white;
text-transform:uppercase;
color:white;
cursor:pointer;
padding:2px;
}
input[type=submit].subbtn:hover{
background:white;
color:rgb(94, 142, 137);
font-weight: bold;
}
table.logintable tr td a{
text-decoration:none;
color:white;
text-transform:uppercase;
padding:5px;
border:1px solid white;
font-weight: bold;
}
table.logintable tr td a:hover{
background:white;
color:rgb(94, 142, 137);
}
div.users{
position:absolute;
bottom:1%;
left:45%;
height:3%;
background:red;
}
a.user, a.admin{
text-transform:uppercase;
text-decoration:none;
background:green;
}
div.users{
border-bottom:1px solid green;
border-right:1px solid green;
border-left:1px solid green;
}
a.user{
border-top:2px solid white;
}
a.admin{
border-top:1px solid green;
}
.mySlides {display:none;}
a.userme{
text-decoration:none;
color:white;
}
a.adminme{
text-decoration:none;
color:white;
}
</style>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="{% static 'css/stylelog.css' %}">
<img src="{% static 'images/title2.png' %}" style="width:100%;margin-top:2%;">
<img src="{% static 'images/title1.png' %}" style="width:60%;margin-left:20%;margin-top:-3%;">
<div class="mainblog">
<img src="{% static 'images/user1.png' %}" style="position:absolute;top:2%;left:35%;">
<form method="post" autocomplete="off">
{% csrf_token %}
<table class="logintable" style="margin-top:50px">
  <tr>
     <td>{{form.username}}</td>
  </tr>
  <tr>
     <td>{{form.password}}</td>
  </tr>
  <tr>
     <td colspan="2" align="center"><input type="submit" value="submit" class="subbtn" /></td>
  </tr>
  <tr>
     <td colspan="2" align="center"><a href="{% url 'users:registration' %}">Register Here</a></td>
  </tr>
</table>
</form>
</div>
<div style="background:green;padding:10px;float:right;position:absolute;top:30%;right:10%;">
<a href="{% url 'users:login' %}" class="userme">User Login</a><br/><br/>
<a href="{% url 'admins:login' %}" class="adminme">Admin Login</a>
</div>
<img src="{% static 'images/logingi.gif' %}" style="position:absolute;top:50%;right:1%;width:30%;">
<div class="w3-content w3-section" style="max-width:500px;margin:0 auto 0 1%;">
  <img class="mySlides" src="{% static 'images/1.png' %}" style="width:80%">
  <img class="mySlides" src="{% static 'images/2.png' %}" style="width:80%">
</div>
<div style="margin-top:150px;background:rgba(94, 142, 137,0.8);border-bottom:1px solid green;border-top:1px solid green;"><marquee behavior="alternate"><p style="color:white;font-size:20px;text-transform:uppercase">Weakly-supervised Deep Embedding for Product Review Sentiment Analysis</p></marquee></div>
<script>
var myIndex = 0;
carousel();

function carousel() {
    var i;
    var x = document.getElementsByClassName("mySlides");
    for (i = 0; i < x.length; i++) {
       x[i].style.display = "none";  
    }
    myIndex++;
    if (myIndex > x.length) {myIndex = 1}    
    x[myIndex-1].style.display = "block";  
    setTimeout(carousel, 2000); // Change image every 2 seconds
}
</script>

{% endblock %}

Mini Project/productreview/assets/templates/productlist.html
{% extends 'base.html' %}
{% block userbody %}
{% load staticfiles %}

<style>
.accordion {
    background-color: #eee;
    color: #444;
    cursor: pointer;
    padding: 18px;
    width: 100%;
    border: none;
    text-align: left;
    outline: none;
    font-size: 15px;
    transition: 0.4s;
}

.active, .accordion:hover {
    background-color: #ccc;
}

.accordion:after {
    content: '\002B';
    color: #777;
    font-weight: bold;
    float: right;
    margin-left: 5px;
}


.panel {
    padding:0 18px;
    background-color: white;
    max-height: 0;
    overflow: hidden;
    transition: max-height 0.2s ease-out;
}
table{
border-collapse:collapse;
border:1px solid green;
}
td{
border-bottom:1px solid green;
padding:2px;
}
th{
background:green;
}
tr:hover{
background:green;
}
.outercas{
height:100%;
width:70%;
padding:10px;
background:rgba(94, 142, 137,0.6);
overflow:auto;
border:2px solid rgb(241, 103, 103);
border-radius:10px;
}
@font-face {
    font-family: Lobster;
    src: url({% static 'fonts/Lobster.otf' %});
}
.para{
text-align:center;
//text-transform:uppercase;
font-size:30px;
width:95%;
float:left;
margin-top:-20px;
color:white;
font-family:Lobster;
}
.titlebar
{
padding:20px;
width:80%;
height:40px;
background:rgba(94, 142, 137,0.8);
margin-bottom:20px;
border:2px solid rgb(241, 103, 103);
border-radius:10px;
}
</style>
</head>
<body>
<div class="titlebar">
<p class="para">Weakly-supervised Deep Embedding for Product Review Sentiment Analysis</p>
</div>
<div class="outercas">
<table>
<tr>
<th>Id</th>
<th>Name</th>
<th>Weight</th>
</tr>
    {% for pr in prod %}
            <tr>
            <td><span style="color:white;">{{forloop.counter}}</span></td>
            <td><span style="color:white;">{{pr.product__name}}</span></td>
            <td><span style="color:white;">{{pr.rati}}</span></td>
    {% endfor %}
        </tr>
    </table>
</div>
{% endblock %}

Mini Project/productreview/assets/templates/signup.html
{% extends 'baselog.html' %}
{% block loginbody %}
{% load staticfiles %}

<style>
.regfor{
background:rgba(94, 142, 137,0.8);
padding:15px;
position:absolute;
bottom:19%;
border:1px solid green;
border-radius:5%;
left:38%;
width:24%;
}
table tr {
height:50px;
}
table{
width: 100%;
}
.common{
background:none;
border:1px solid white;
text-align:center;
width:100%;
border-radius:2px;
}
input{
height:30px;
}
input[type=submit]{
width:100px;
background:none;
border:1px solid white;
color:white;
text-transform:uppercase;
border-radius:5px;
}
input[type=submit]:hover{
background:white;
color:rgb(94, 142, 137);
font-weight: bold;
}
::placeholder{
color:white;
}
table.usrtbl{
margin-top:46%;
}
</style>
<script>
window.onload = function() {
    var src = document.getElementById("id_password1"),
        dst = document.getElementById("id_password2");
    src.addEventListener('input', function() {
        dst.value = src.value;
    });
};

</script>
<img src="{% static 'images/title2.png' %}" style="width:100%;margin-top:-1%;">
<img src="{% static 'images/title1.png' %}" style="width:60%;margin-left:20%;margin-top:-3%;">
<img src="{% static 'images/archi.png' %}" style="width:35%;position:absolute;top:30%;left:1%;">
<div class="regfor">
<img src="{% static 'images/adduser.png' %}" style="position:absolute;top:2%;left:33%;">
<form method="post" autocomplete="off">
{% csrf_token %}
<table class="usrtbl">
<tr>
<td>{{form.first_name}}</td>
</tr>
<tr>
<td>{{form.last_name}}</td>
</tr>
<tr>
<td>{{form.username}}</td>
</tr>
<tr>
<td>{{form.password}}</td>
</tr>
<tr>
<td>{{form.password1}}</td>
</tr>
<tr style="visibility:collapse;">
<td>{{form.password2}}</td>
</tr>
<tr>
<td>{{form.email}}</td>
</tr>
<tr>
<td>{{form.birth_date}}</td>
</tr>
<tr>
<td align="center"><input type="submit" value="submit" /></td>
</tr>
</table>
</form>
</div>
<img src="{% static 'images/signup.gif' %}" style="position:absolute;right:5%;top:45%;">
<div style="position:absolute;bottom:1px;width:99%;background:rgba(94, 142, 137,0.8);border-bottom:1px solid green;border-top:1px solid green;"><marquee behavior="alternate"><p style="color:white;font-size:20px;text-transform:uppercase">Weakly-supervised Deep Embedding for Product Review Sentiment Analysis</p></marquee></div>
{% endblock %}

Mini Project/productreview/assets/templates/topproducts.html
{% extends 'base.html' %}
{% block userbody %}
{% load staticfiles %}

<style>
.accordion {
    background-color: #eee;
    color: #444;
    cursor: pointer;
    padding: 18px;
    width: 100%;
    border: none;
    text-align: left;
    outline: none;
    font-size: 15px;
    transition: 0.4s;
}

.active, .accordion:hover {
    background-color: #ccc;
}

.accordion:after {
    content: '\002B';
    color: #777;
    font-weight: bold;
    float: right;
    margin-left: 5px;
}


.panel {
    padding:0 18px;
    background-color: white;
    max-height: 0;
    overflow: hidden;
    transition: max-height 0.2s ease-out;
}
table{
border-collapse:collapse;
border:1px solid green;
}
td{
border-bottom:1px solid green;
padding:2px;
}
th{
background:green;
}
tr:hover{
background:#CCCCCC;
}
</style>
</head>
<body>

{% for val in vallit %}
<button class="accordion">{{val.category}}</button>
<div class="panel">
<table>
<tr>
<th>Name</th>
<th>Weight</th>
<th>Color</th>
<th>Price</th>
<th>Stock</th>
<th>Image</th>
<th>Description</th>
</tr>
    {% for pr in prod %}
        {% if pr.category == val.category %}
            <tr>
            <td>{{pr.name}}</td>
            <td>{{pr.weight}}</td>
            <td>{{pr.color}}</td>
            <td>{{pr.price}}</td>
            <td>{{pr.stock}}</td>
            <td><img src="{{pr.images.url}}" style="width:100px;height:100px;" /></td>
            <td>{{pr.description}}</td>
        {% endif %}
    {% endfor %}
        </tr>
    </table>
</div>
{% endfor %}

<script>
var acc = document.getElementsByClassName("accordion");
var i;

for (i = 0; i < acc.length; i++) {
  acc[i].addEventListener("click", function() {
    this.classList.toggle("active");
    var panel = this.nextElementSibling;
    if (panel.style.maxHeight){
      panel.style.maxHeight = null;
    } else {
      panel.style.maxHeight = panel.scrollHeight + "px";
    } 
  });
}
</script>


{% endblock %}

Mini Project/productreview/assets/templates/yourorders.html
{% extends 'base.html' %}
{% block userbody %}
{% load staticfiles %}
<style>

.titlebar
{
padding:20px;
width:100%;
height:100px;
background:rgba(94, 142, 137,0.8);
margin-bottom:20px;
border:2px solid rgb(241, 103, 103);
border-radius:10px;
}
div.titlebar img.usicon{
position:relative;
left:17%;
}
div.titlebar img.caicon{
position:relative;
margin-left:3%;
}
@font-face {
    font-family: Lobster;
    src: url({% static 'fonts/Lobster.otf' %});
}
.para{
text-align:center;
//text-transform:uppercase;
font-size:30px;
width:75%;
float:left;
margin-top:-20px;
color:white;
font-family:Lobster;
}
.containersd{
width:100%;
margin-left:-50px;
}
.outercas{
height:100%;
width:100%;
background:rgba(94, 142, 137,0.6);
overflow:auto;
border:2px solid rgb(241, 103, 103);
border-radius:10px;
}
</style>
<link rel="stylesheet" href="{% static 'css/bootstrap1.min.css' %}">
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
<div class="containersd">
<div class="titlebar">
<p class="para">Weakly-supervised Deep Embedding for Product Review Sentiment Analysis</p>
<a href="{% url 'users:chechouts' %}" class="comico" style="margin-left:40px;margin-top:-40px;"><img src="{% static 'images/checkout.png' %}" style="width:80px;height:80px;"/></a>
</div>
<div class="outercas">
<table>
<tr>
    <th>Product Name</th>
    <th>Image</th>
    <th>Qty</th>
    <th>Location</th>
    <th>Ordered Date</th>
    <th colspan="2">Update / Cancel</th>
</tr>
{% for pr in pror %}
<tr>
<td>{{pr.prod.name}}</td>
<td><img src="{{pr.prod.images.url}}" style="width:100px;height:100px;" /></td>
<td>{{pr.prodqty}}</td>
<td>{{pr.location}}</td>
<td>{{pr.dateordered}}</td>
<td><a class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal{{pr.id}}">Update</a></td>
<td>
<form method="POST" autocomplete="off">
{% csrf_token %}
<input type="hidden" name="idys" value="{{pr.id}}">
<button type="submit" name="cancel"  class="btn btn-info btn-lg">Cancel</button></td>
</form>
 <div class="modal fade" id="myModal{{pr.id}}" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Modal Header</h4>
        </div>
        <div class="modal-body">
          
          
          
          
       <img src="{{pr.prod.images.url}}"  style="height:250px;width:565px;"><br/>
          {{pr.prod.name}}<br/>
          {{pr.prod.price}}<br/>
          {{pr.prod.category}}<br/>
          {{pr.prod.stock}}<br/>
          <form method="POST" autocomplete="off">
          {% csrf_token %}
          <input type="number" name="qty" value="{{pr.prodqty}}" placeholder="Enter The Number of Quantity" required><br/><br/>
          <input type="text" name="loc" value="{{pr.location}}" placeholder="Enter The Location" required><br/>
          <input type="hidden" name="idy" value="{{pr.id}}"><br/>

        </div>
        <div class="modal-footer">
          <button type="submit" name="updates" class="btn btn-default">Update</button>
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          </form>
        </div>
      </div>
      
    </div>
  </div>

{% endfor %}
</tr>
</table>
</div>
</div>

{% endblock %}